### ISSUE TITLE
Fix basic types and their names

### ISSUE THREAD

**Issue by ntruessel** [lizard-project/lizard-language#4]
We should reach consensus about which basic types we want to offer and how they should be named

**Comment by F1rst-Unicorn** [comment]
My suggestion would be Int_$, where $ is one of 8,16,32,64 for signed integers, maybe adding Word_$ for unsigned, Bool, Single and Double for 32 and 64 bit IEEE floating point types.

**Comment by ntruessel** [comment]
I like `Int_$`, `Bool`, but prefer `Unsigned_$` over `Word_$`. For consistency I suggest naming floating point types `Float_$` (only 32 and 64 bit here).

**Comment by F1rst-Unicorn** [comment]
`Float_$` is ok, but I don't like an adjective used as a data type's name. Maybe `Natural_$`?

**Comment by ntruessel** [comment]
I proposed `unsigned` because it is more widely used and understood as `natural` (which would mathematically be more correct). `Bool` is an abreviation of an adjective, `Float_$` is a verb.

**Comment by F1rst-Unicorn** [comment]
Ok, so to summarise: `Int_$`, `Unsigned_$`, `Bool` and `Float_$`

**Comment by ntruessel** [comment]
That's what I proposed. What we forgot about: characters. Do we want them to be `Int_$` or should they be a custom type? I'd prefer the latter for better semantics

**Comment by ntruessel** [comment]
Or should character be some class and we fix some charset like UTF-8/UTF-16/ASCII (where I strongly discourage ASCII, UTF-8 is hard because of flexible char width, UTF-16 often wastes a lot of space)

**Comment by F1rst-Unicorn** [comment]
Or we simply drop characters and only allow for string operations. If a certain encoding is needed we can provide a string API that returns some Unsigned[] array which represents the correct encoding
